# Generated by Django 3.1 on 2020-09-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_comment', models.CharField(max_length=255)),
                ('clent_image', models.ImageField(upload_to='client_images/')),
            ],
            options={
                'db_table': 'client_details',
            },
        ),
        migrations.DeleteModel(
            name='ClientsComment',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='category_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='Image',
            new_name='images',
        ),
    ]
